name: dart_art
description: Experience Dart’s coding aesthetics here, which contains lots of useful utils.
version: 0.1.0+1
repository: https://github.com/Dynesshely/DartArt

environment:
  sdk: ^3.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
