name: flutter_zofo
description: "A simple flutter quick dev tool"
version: 0.0.1
homepage: https://github.com/Dynesshely/DartArt
repository: https://github.com/Dynesshely/DartArt

environment:
  sdk: ^3.7.2
  flutter: ">=1.17.0"

dependencies:
  badges: ^3.1.2
  cherrilog: ^0.3.1
  community_material_icon: ^5.9.55
  concentric_transition: ^1.0.3
  connectivity_plus: ^6.1.4
  crypto: ^3.0.6
  dart_art: ^0.1.2
  device_info_plus: ^11.4.0
  drift: ^2.25.1
  expansion_tile_group: ^2.2.0
  faker: ^2.2.0
  fl_chart: ^1.0.0
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.32.2
  flutter_chat_ui: ^2.1.3
  flutter_sharing_intent: ^1.1.1
  flutter_typeahead: ^5.2.0
  get: ^4.7.2
  intl: ^0.20.2
  network_info_plus: ^6.1.4
  package_info_plus: ^8.3.0
  path: ^1.9.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  pinyin: ^3.3.0
  sensors_plus: ^6.1.1
  shared_preferences: ^2.5.3
  sliding_up_panel: ^2.0.0+1
  sqlite3_flutter_libs: ^0.5.31
  url_launcher: ^6.3.1
  vector_math: ^2.1.4
  vibration: ^3.1.3
  wakelock_plus: ^1.3.2

dev_dependencies:
  build_runner: ^2.4.15
  drift_dev: ^2.26.1
  flutter_gen: ^5.10.0
  flutter_lints: ">=5.0.0 <7.0.0"
  flutter_test:
    sdk: flutter
  import_sorter: ^4.6.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true

  assets:
    - assets/

  generate: true

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
