name: flutter_zofo_test
description: "A new Flutter project to test Zofo framework"
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_zofo:
    path: ../flutter_zofo

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  import_sorter: ^4.6.0

flutter:
  uses-material-design: true
